version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - portfolio-network

  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - portfolio-network

volumes:
  mysql-data:
  redis-data:

networks:
  portfolio-network:
    driver: bridge

    #  app:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #    container_name: portfolio-app
    #    restart: always
    #    ports:
    #      - "8080:8080"
    #    depends_on:
    #      - mysql
    ##      - redis
    #    environment:
    #      SPRING_PROFILES_ACTIVE: docker
    #      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
    #      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
    #      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    #      SPRING_REDIS_HOST: redis
    #      SPRING_REDIS_PORT: 6379
    #    networks:
    #      - portfolio-network
