spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3307/portfolio_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: portfolio_user
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0

kakao:
  login:
    api_key: ${KAKAO_REST_API_KEY:}
    client_secret: ${KAKAO_CLIENT_SECRET:}
    uri:
      base: https://kauth.kakao.com
    admin_key: ${KAKAO_ADMIN_KEY:}

oauth:
  kakao:
    redirect-uris:
      - http://localhost:3000/callback

jwt:
  secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_TTL:3600000}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_TTL:1209600000}
  use-cookie: ${JWT_USE_COOKIE:false}

cookie:
  domain: ${COOKIE_DOMAIN:localhost}
  secure: ${COOKIE_SECURE:false}
  http-only: ${COOKIE_HTTP_ONLY:true}
  same-site: ${COOKIE_SAME_SITE:Lax}
  max-age: ${COOKIE_MAX_AGE:604800}

logging:
  level:
    org.springframework.security: DEBUG
    io.resume: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

jwt:
  use-cookie: true

cookie:
  secure: true
  same-site: None

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

kakao:
  login:
    api_key: test_api_key
    client_secret: test_client_secret
    uri:
      base: https://kauth.kakao.com
    admin_key: test_admin_key

oauth:
  kakao:
    redirect-uris:
      - http://localhost:3000/callback
      - http://test.com/callback

jwt:
  secret: test-secret-key-for-jwt-token-minimum-32-characters-long
  access-token-expiration-time: 3600000
  refresh-token-expiration-time: 1209600000
  use-cookie: false

cookie:
  domain: localhost
  secure: false
  http-only: true
  same-site: Lax
  max-age: 604800

logging:
  level:
    org.springframework.security: INFO
    io.resume: DEBUG
